const arr = [
  // defualt
    {name: '원주' ,province: "강원"},
  // 서울
    {name: '서울경부' ,province: "서울"},
    {name: '동서울' ,province: "서울"},
    {name: '김포공항' ,province: "서울"},
    {name: '상봉' ,province: "서울"},
    // 인천/경기
    {name: '인천' ,province: "인천/경기"},
    {name: '인천공항T1' ,province: "인천/경기"},
    {name: '성남종합' ,province: "인천/경기"},
    {name: '수원터미널' ,province: "인천/경기"},
    {name: '안산' ,province: "인천/경기"},
    {name: '이천' ,province: "인천/경기"},
    {name: '용인' ,province: "인천/경기"},
    {name: '인천공항T2' ,province: "인천/경기"},
    {name: '고양종합' ,province: "인천/경기"},
    {name: '고천' ,province: "인천/경기"},
    {name: '공도' ,province: "인천/경기"},
    {name: '광주(경기)' ,province: "인천/경기"},
    {name: '구리' ,province: "인천/경기"},
    {name: '대림동산' ,province: "인천/경기"},
    {name: '부천' ,province: "인천/경기"},
    {name: '성남종합' ,province: "인천/경기"},
    {name: '송탄' ,province: "인천/경기"},
    {name: '수원터미널' ,province: "인천/경기"},
    {name: '안산' ,province: "인천/경기"},
    {name: '안성' ,province: "인천/경기"},
    {name: '안양' ,province: "인천/경기"},
    {name: '여주' ,province: "인천/경기"},
    {name: '오산' ,province: "인천/경기"},
    {name: '용인' ,province: "인천/경기"},
    {name: '우만동' ,province: "인천/경기"},
    {name: '의정부' ,province: "인천/경기"},
    {name: '이천' ,province: "인천/경기"},
    {name: '일죽' ,province: "인천/경기"},
    {name: '죽산' ,province: "인천/경기"},
    {name: '중앙대(안성)' ,province: "인천/경기"},
    {name: '평택' ,province: "인천/경기"},
    {name: '하남BRT' ,province: "인천/경기"},
    {name: '호계동' ,province: "인천/경기"},
    // 강원
    {name: '강릉고속' ,province: "강원"},
    {name: '강릉시외' ,province: "강원"},
    {name: '고한사북공영' ,province: "강원"},
    {name: '공근' ,province: "강원"},
    {name: '귀래' ,province: "강원"},
    {name: '내덕' ,province: "강원"},
    {name: '녹전' ,province: "강원"},
    {name: '대화' ,province: "강원"},
    {name: '동산' ,province: "강원"},
    {name: '동해' ,province: "강원"},
    {name: '둔내' ,province: "강원"},
    {name: '미탄' ,province: "강원"},
    {name: '방림삼거리' ,province: "강원"},
    {name: '백담사' ,province: "강원"},
    {name: '북방' ,province: "강원"},
    {name: '삼척' ,province: "강원"},
    {name: '상동' ,province: "강원"},
    {name: '속초' ,province: "강원"},
    {name: '신남' ,province: "강원"},
    {name: '쌍용' ,province: "강원"},
    {name: '연당' ,province: "강원"},
    {name: '영월' ,province: "강원"},
    {name: '원주공항' ,province: "강원"},
    {name: '원통' ,province: "강원"},
    {name: '인제' ,province: "강원"},
    {name: '장평' ,province: "강원"},
    {name: '정선' ,province: "강원"},
    {name: '진부' ,province: "강원"},
    {name: '춘천' ,province: "강원"},
    {name: '춘천병원' ,province: "강원"},
    {name: '태백' ,province: "강원"},
    {name: '평창' ,province: "강원"},
    {name: '홍천' ,province: "강원"},
    {name: '횡계' ,province: "강원"},
    {name: '횡성' ,province: "강원"},
    {name: '흥업' ,province: "강원"},
    // 대전 충남 
    {name: '대전복합' ,province: "대전/충남"},
    {name: '천안' ,province: "대전/충남"},
    {name: '유성시외' ,province: "대전/충남"},
    {name: '세종청사' ,province: "대전/충남"},
    {name: '공주' ,province: "대전/충남"},
    {name: '세종터미널' ,province: "대전/충남"},
    // 충북
    {name: '청주시외' , province: "충북"},
    {name: '충주' , province: "충북"},
    // 광주/전남
    {name: '광주' , province: "광주/전남"},
    // 전북
    {name: '전주' , province: "전북"},
    // 부산/경남
    {name: '부산서부' , province: "부산/경남"},
    {name: '창원' , province: "부산/경남"},
    {name: '진주' , province: "부산/경남"},
    {name: '마산' , province: "부산/경남"},
    // 대구/경북
    {name: '동대구' , province: "대구/경북"},
    {name: '구미' , province: "대구/경북"},
    {name: '대구서부' , province: "대구/경북"},
    {name: '포항' , province: "대구/경북"},
  ];

